### PR TITLE
Dbz 1668

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1668

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey, this doesn't seem to change much for me. My screen width is 2880 FWIW; it still looks exactly like in the screenshot I shared in the JIRA issue.

**Comment by Naros** [comment]
Ah; then your monitor width is in between the standard break points I added, so I'll need to add more breakpoints I suppose.  I just added 2560/3840 but looking at https://en.wikipedia.org/wiki/Graphics_display_resolution, I probably should add a 3200 and 3440 breakpoint.  I'll add those and let you check.

**Comment by gunnarmorling** [comment]
So I'm wondering whether those fixed break points are the best approach. Perhaps the right-hand sight menu should just be attached to the right side of the window, giving all scaling wider and narrower space to the middle part with the actual contents. E.g. as done in the Bootstrap docs: https://getbootstrap.com/docs/4.1/getting-started/introduction/. WDYT?

**Comment by Naros** [comment]
My memory is a bit foggy but I thought we went down that path sometime back in August or so when we first attempted the ToC changes and there was a reason we went with this approach.  I'd have to look back through the PR comments to see, but I can certainly look into seeing if we could make that work instead.

**Comment by gunnarmorling** [comment]
Yes, that would be my preference. Unfortunately, I also don't quite remember why we didn't go for this back then. But it seems just so wasteful if that space on the right isn't used why the main column is so narrow.

**Comment by Naros** [comment]
This PR is superseded by https://github.com/debezium/debezium.github.io/pull/409, closing in favor of the new implementation in the new PR.

**Pull request closed without merging**
