### PR TITLE
Fixes typos in the FAQ documentation

### PR DESCRIPTION
**Pull request by eric-weaver**
Addresses a few typos found on the FAQ documentation

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Nice, thanks a lot, @eric-weaver.

Btw., seeing your GH organizations, I remember reading about a meet-up at JW Player in New York earlier this year where supposedly Debezium was discussed. Do you happen to know by any chance whether there's a recording and/or slides of this available online somewhere? Thanks!

**Comment by eric-weaver** [comment]
Hey @gunnarmorling, you're correct! Actually I was a co-presenter of that meet-up you're referring to. I'm working on getting a publicly accessible copy of presentation for you

**Comment by gunnarmorling** [comment]
Ha, that'd be excellent!

**Comment by eric-weaver** [comment]
@gunnarmorling Sorry about the delay, but had to wait on this blog post (also references our Debezium usage) https://medium.com/jw-player-engineering/southpaw-176aea5f4583. 

Links can be found within the blog post, but here's the link to the presentation video and slides
https://content.jwplatform.com/previews/im6UlLR3-mA0mA2gk
https://www.slideshare.net/jwplayer/polylog-a-logbased-architecture-for-distributed-systems-124997666

**Comment by gunnarmorling** [comment]
Ah, very nice, thanks for sharing! Added this to my "to read" list,
denormalization is a super-interesting topic to many Debezium users.

**Pull request merged**
