### PR TITLE
Added my example code involving Debezium

### PR DESCRIPTION
**Pull request by nmertaydin**
Added my example code "MySQL Debezium Kafka Pinot CDC Flow" @ https://github.com/nmertaydin/mysql-debezium-vs-maxwell-kafka-pinot

### CODE REVIEW

**Comment by jpechane** [comment]
@nmertaydin Applied, thanks a lot!

**Comment by nmertaydin** [comment]
> 😭 Deploy PR Preview [5530328](https://github.com/debezium/debezium.github.io/commit/553032850331e531acbb1fb3b0fb72497493b5c0) failed. [Build logs](https://github.com/debezium/debezium.github.io/actions/runs/1648778195)
> 
> [](https://github.com/debezium/debezium.github.io/runs/4689696062)
> 
> 🤖 By [surge-preview](https://github.com/afc163/surge-preview)

Oops @jpechane is this something known? ❓

**Comment by gunnarmorling** [comment]
No worries, @nmertaydin; sometimes the clean-up of the staging environment fails for reasons unrelated to the specific change at hand. I just cleaned it up. Thanks for adding your example!

**Comment by nmertaydin** [comment]
> No worries, @nmertaydin; sometimes the clean-up of the staging environment fails for reasons unrelated to the specific change at hand. I just cleaned it up. Thanks for adding your example!

You're welcome. 🙇

**Pull request merged**
