### PR TITLE
DBZ-286 Connection keepAlive support

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by rhauch** [comment]
@jpechane, are these changes for 0.5.1, or should they be enqueued and merged only when the next Debezium release is made?

**Comment by gunnarmorling** [comment]
This is for 0.5.2, so we should hold back the merge. Planning for 0.5.2 some time next week.

**Comment by gunnarmorling** [comment]
I've created and assigned to this PR a new label "merge after next release". Let's assign it when filing PRs such as this one.

**Comment by gunnarmorling** [comment]
Merged now that 0.5.2 is out. Thanks, @jpechane!

**Pull request merged**
