### PR TITLE
[DBZ-1193] Updated the Postgres Doc for added column support for network address types.

### PR DESCRIPTION
**Pull request by ShubhamRwt**
Updated the Postgres Docs for added support for network address types

### CODE REVIEW

**Comment by Wang-Yu-Chao** [comment]
Hi @ShubhamRwt, would you mind adding two new types `MACADDR` and `MACADDR8` together to the doc? Something like:
```
|`MACADDR`
|`STRING`
|
|MAC addresses
	
|`MACADDR8`
|`STRING`
|
|MAC addresses in EUI-64 format
```
Many thanks!

**Comment by ShubhamRwt** [comment]
Yes Sure I will do it .

**Comment by ShubhamRwt** [comment]
@gunnarmorling and @Wang-Yu-Chao. I have updated the docs with the added support of MACADDR and MACADDR8.

**Comment by gunnarmorling** [comment]
Excellent, thanks!

**Comment by ShubhamRwt** [comment]
@gunnarmorling I have squashed the commits into one.

**Comment by gunnarmorling** [comment]
Thanks, @ShubhamRwt. This should have been merged long time ago, no idea why we forgot about it. Thanks again!

**Pull request merged**
