### PR TITLE
Update online-resources.asciidoc

### PR DESCRIPTION
**Pull request by Amitbhave**
Course on Debezium - Atlas mongodb on Udemy

### CODE REVIEW

**Review by gunnarmorling — COMMENTED** [review]
Do you indeed want to include the referral code into the URL?

**Comment by Amitbhave** [comment]
@gunnarmorling I actually shared the course URL from my udemy dashboard! 😅 You can keep it if it's okay with you!

**Comment by Naros** [comment]
Hi @Amitbhave, I'm inclined to suggest we remove the referral code unless there is some requirement for it to exist.

**Comment by Amitbhave** [comment]
@Naros done!

**Pull request merged**
