### PR TITLE
DBZ-4011 Add GitHub actions to preview website via surge.sh

### PR DESCRIPTION
**Pull request by uidoyen**
tested PR on staging https://github.com/debezium/debezium.github.io/pull/716

### CODE REVIEW

**Comment by jpechane** [comment]
@uidoyen Nice feature thanks! Do I need to merge only this PR and the other shoudl be dropped or should both be merged?
Could you please add this to our documentation? Both `README` and `CONTRIBUTING` so the contributors know how to check their docs changes.

Thanks!

**Comment by uidoyen** [comment]
> @uidoyen Nice feature thanks! Do I need to merge only this PR and the other shoudl be dropped or should both be merged?
> Could you please add this to our documentation? Both `README` and `CONTRIBUTING` so the contributors know how to check their docs changes.
> 
> Thanks!

@jpechane Updated both README and CONTRIBUTING doc.

**Comment by jpechane** [comment]
@uidoyen Applied, thanks!

**Comment by jpechane** [comment]
@uidoyen Could you please check https://github.com/debezium/debezium.github.io/actions/runs/1257431284

**Pull request merged**
