### PR TITLE
WIP: Use new Adobe Analytics

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane As it says "WIP" - what's still missing, and what's the plan for finishing it?

**Comment by clt2rdu** [comment]
The legacy s.code Adobe shutoff date is January 30th.  Marketing IT is working on mock scripts that do not make any service calls (i.e. they will no longer do any tracking).  The substituted mock scripts should not cause failures on your site but to mitigate any potential of failures, we are asking properties referencing these legacy scripts to remove them.  I wanted to let you know that the scripts you have on your site will stop working on January 30th which means you will no longer have Adobe analytics tracking unless you move to the new method (DPAL) before that date.  This requires removing the legacy scripts for DPAL to work.

**Comment by clt2rdu** [comment]
@jpechane , I wanted to check on the status of this request?  We turned off the legacy Adobe Analytics and Eloqua scripts so those legacy scripts on your site are no longer firing. By adding the new method to fire off Adobe Analytics, you would be able to see how visitors to your site engage with our main sites like access.redhat.com, developers.redhat.com, etc.

**Comment by gunnarmorling** [comment]
Hey @clt2rdu, do you have any info on how we'd do this: "adding the new method"? And how could we see the results? Could you send me an email to my Red Hat address with the details perhaps? Thanks!

**Comment by gunnarmorling** [comment]
Closing this for now, as no new community projects are onboarded to the Adobe Analytics system atm. We've removed all the legacy code as part of the ongoing migration to Jekyll, which should go live tomorrow. Thanks all. Not sure whether I feel more embarrassed or happy about closing this PR as "won't fix" after 2 years ;)

**Pull request closed without merging**
