### PR TITLE
DBZ-857 Update UnwrapFromEnvelope SMT documentation

### PR DESCRIPTION
**Pull request by maver1ck**

### CODE REVIEW

**Comment by jpechane** [comment]
@maver1ck Thanks! Could you please reword the commit message to contain the issue id and short description - more or less the same as https://github.com/debezium/debezium/commit/947abf9815438ee3d5d2597b09fa6f05336e09d5

**Comment by maver1ck** [comment]
@jpechane 
Done

**Comment by jpechane** [comment]
@maver1ck Will apply at the release, thank!

**Comment by gunnarmorling** [comment]
Merged, as we decided to ship this as part of today's 0.8.3.Final release.

**Pull request merged**
