### PR TITLE
Blog Cassandra CDC contribution

### PR DESCRIPTION
**Pull request by criccomini**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Very nice, thanks a lot, @criccomini! Any chance that you add the images from the original post, too?

**Comment by criccomini** [comment]
Updated

**Comment by jpechane** [comment]
@criccomini HI, thanks a lot. I'll review it in more detail later today - mostly formatting verification. In the meantime I've pushed the links to the original posts.

**Comment by jpechane** [comment]
@criccomini LGTM, thanks. I don't see any visual defects so it can be published.
@gunnarmorling I've added *canonicals* support. Please check if you are happy with it and merge.

**Comment by Naros** [comment]
@jpechane This looks good to me, I can either merge or we can wait for Gunnar; up to you.

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks a lot everyone; should be live on debezium.io in a bit.

**Comment by criccomini** [comment]
LGTM

**Pull request merged**
