### PR TITLE
DBZ-1458 Adding architecture page

### PR DESCRIPTION
**Pull request by gunnarmorling**
@jpechane, @Naros, as dicussed last week, here's the architecture page for the website.

https://issues.jboss.org/browse/DBZ-1458

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Pushed something for the features page, too. Let me know if there's something you think should be added.

**Comment by gunnarmorling** [comment]
About the "concept" page, I'm not sure; perhaps it should just be removed? Wouldn't know what to add there, which isn't yet on "architecture" and "features". WDYT?

**Comment by Naros** [comment]
@gunnarmorling I completely agree with removing _concepts_.  I think having the features and architecture pages should suffice for what we need as we can always add to it later on.

**Comment by gunnarmorling** [comment]
Ok; could you then perhaps add a commit for removing the page + menu item
and push it to this PR? Thanks!

>

**Comment by gunnarmorling** [comment]
@Naros, I reckon we can close this as it's incorporated in your docs rework PR #339?

**Comment by Naros** [comment]
That's correct, closing this PR.

**Pull request closed without merging**
