### PR TITLE
Updated the version drop-down order in release breadcrumb

### PR DESCRIPTION
**Pull request by indraraj**

### CODE REVIEW

**Review by uidoyen — APPROVED** [review]
Tested locally. Looks good.

**Comment by mdrillin** [comment]
@indraraj  -  why was the ordering reversed here?  It is a deviation from the original site, did someone request the change?

versionReversal

**Comment by gunnarmorling** [comment]
> did someone request the change?

Yes, I did :) See https://github.com/debezium/debezium.github.io/issues/563 (good idea btw. to always reference the corresponding issue in commit messages). The motivation being to have the newest one always at the top (also consistent with the ordering in the docs).

**Comment by mdrillin** [comment]
Ok, makes sense - thanks!

**Pull request merged**
