### PR TITLE
Add k-mean clustring with Flink and Spark blog post

### PR DESCRIPTION
**Pull request by vjuranek**

### CODE REVIEW

**Comment by Naros** [comment]
@vjuranek is this ready for a review?

**Comment by vjuranek** [comment]
@Naros yes, I was only messing up with the correct size of the image

**Comment by Naros** [comment]
@vjuranek, please feel free to publish on Monday once you've merged your example repository that accompanies this.  I applied some grammar-based edits directly as it was probably easier than trying to do that all via the PR.

**Review by Naros — APPROVED** [review]

**Comment by vjuranek** [comment]
Thanks a lot for review and grammar fixes @Naros !

**Pull request merged**
