### PR TITLE
Fixing responsive issues

### PR DESCRIPTION
**Pull request by uidoyen**
Fixed scrollbar issues on mobile view

Screenshot from 2020-11-20 13-45-43
Fixed banner padding issue
banners

### CODE REVIEW

**Comment by mdrillin** [comment]
I'm seeing a formatting issue with the banner text at full screen now
banner
...

**Comment by uidoyen** [comment]
> I'm seeing a formatting issue with the banner text at full screen now
> banner
> ...

Fixed. It should look good now.

**Comment by uidoyen** [comment]
> I'm seeing a formatting issue with the banner text at full screen now
> banner
> ...

Screenshot from 2020-11-23 12-14-18

Fixed. It should look good now.

**Review by indraraj — APPROVED** [review]
Tested locally, looks good.

**Pull request merged**
