### PR TITLE
DBZ-574 Panel with 7 latest blogposts

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-574

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Wow, that was quick :) The menu is cool, but there's quite some whitespace between the menu and the actual contents, making the column with the latter quite narrow. Any chance to have a bit less whitespace for the sake of more width for the contents?

**Comment by jpechane** [comment]
@gunnarmorling There's always a chance :-). I tried my best so hopefully it is ok now

**Comment by jpechane** [comment]
@gunnarmorling Anyfurther comments on this? Are the margins still too big?

**Comment by gunnarmorling** [comment]
@jpechane Yeah, looks much better now. Could we only have the same amount of padding on the right side of the text as on the left side of the menu? I think then it'd be perfect. And it'd also need a rebase to current HEAD. Thanks!

**Comment by gunnarmorling** [comment]
screen shot 2018-03-09 at 22 26 12

To clarify that's what I meant. The padding on the left side is great, would be nice to have the same on the right side, too.

**Comment by jpechane** [comment]
@gunnarmorling Rebased and made padding on both sides

**Comment by gunnarmorling** [comment]
Looks great! Thanks, @jpechane!

**Pull request merged**
