### PR TITLE
Adding 0.7.2 release announcement and project roadmap

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by jpechane** [comment]
Blogpost is fine, just please add link to the issues describing the limitations. You have there one for MongoDB flattening but you mention others in text.

**Comment by gunnarmorling** [comment]
Do you just mean shortcomings of the Mongo SMT, or yet something else?

**Comment by jpechane** [comment]
Geospatial arrays too

**Comment by jpechane** [comment]
A roadmap is fine but I think to would be cool to have a picture like this https://time.graphics/line/52162

**Comment by gunnarmorling** [comment]
Interesting idea. It'd requires us to stick specific release dates to it,
though. Let's keep that for a follow-up :)

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks for reviewing, @jpechane!

**Pull request closed without merging**
