### PR TITLE
DBZ-4214 GH Action for tearing down abandoned website preview

### PR DESCRIPTION
**Pull request by uidoyen**
https://issues.redhat.com/browse/DBZ-4214

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM, but this part discussed in the issue still seems to be missing:

> This action should also log out the URLs of all the currently existing preview environments. 

I'd suggest to 

* first tear down the specified environment, then display the remaining ones (if any)
* if no environment has been specified, simply display any existing ones (if any)

**Comment by uidoyen** [comment]
@gunnarmorling Updated accordingly.

**Comment by gunnarmorling** [comment]
Applied, thx!

**Comment by gunnarmorling** [comment]
Ok, so this generally works, thanks. Could you only make the PR number optional and skip the tear down step if none is given, only displaying the existing environments? Also adjust the parameter description to something like "PR number to tear down; omit to list all existing preview environments". No need for another PR review cycle for that, please just merge that change yourself and resolve the issue in Jira after that. Thx!

**Pull request merged**
