### PR TITLE
DBZ-6216 New images only on Quay.io

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-6216

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros Could you please take a look at this one? The content LGTM. If fine for you could you please merge it and sync it with a at least Twitter message?

@vjuranek Could you please send an announcement to the mailing list and create a new topic in the users stream when this is published?

**Comment by vjuranek** [comment]
@jpechane @Naros please review again if everything is accurate. Thanks!

**Comment by jpechane** [comment]
LGTM, let's merge it after the release.

**Review by Naros — APPROVED** [review]

**Review by jpechane — APPROVED** [review]
@vjuranek Fine for me thanks!

@Naros I envision publishing this 1-2 days after 2.2.0.Final relase announcement. WDYT?

**Pull request merged**
