### PR TITLE
DBZ-3897 Update UI to re-org URL

### PR DESCRIPTION
**Pull request by uidoyen**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@uidoyen, any thoughts on the build failure?

**Comment by gunnarmorling** [comment]
@uidoyen, assuming this build failure gets fixed, can this then be previewed via the new PR preview? Does it require the PRs in the main repo to be merged first? If so, if we merge them _without_ this change here yet, what's the implication on the published site? Essentially, I'm trying to figure how to preview/review the stuff without breaking the published site :)

**Comment by gunnarmorling** [comment]
Alternatively, we can also do a quick screen share session if you can show me everything from your local machine. WDYT?

**Comment by gunnarmorling** [comment]
@uidoyen, do we still need this PR?

**Comment by gunnarmorling** [comment]
Hey @uidoyen, could you clarify whether this PR still is needed? Or should we just close it?

**Comment by uidoyen** [comment]
Handled in the following PR https://github.com/debezium/debezium.github.io/pull/734 hence closing this.

**Pull request closed without merging**
